In [1]:
import pandas as pd
import nltk
import re

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
data = pd.read_csv(r"C:\Users\DELL\Downloads\Movies_review.xls")

In [8]:
data.head()

   Unnamed: 0                                             review  target
0           0  plot : two teen couples go to a church party ,...       0
1           1  the happy bastard's quick movie review \ndamn ...       0
2           2  it is movies like these that make a jaded movi...       0
3           3   " quest for camelot " is warner bros . ' firs...       0
4           4  synopsis : a mentally unstable man undergoing ...       0

In [9]:
data.info()
data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2000 non-null   int64
 1   review      2000 non-null   object
 2   target      2000 non-null   int64
dtypes: int64(2), object(1)
memory usage: 47.0+ KB

(2000, 3)

In [14]:
# One positive review

In [15]:
print("Positive Review:\n")
print(data[data['target'] == 1]['review'].iloc[0])

Positive Review:

films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before .
for starters , it was created by alan moore ( and eddie campbell ) , who brought the medium to a whole new level in the mid '80s with a 12-part series called the watchmen .
to say moore and campbell thoroughly researched the subject of jack the ripper would be like saying michael jackson is starting to look a little odd .
the book ( or " graphic novel , " if you will ) is over 500 pages long and includes nearly 30 more that consist of nothing but footnotes .
in other words , don't dismiss this film because of its source .
if you can get past the whole comic book thing , you might find another stumbling block in from hell's directors , albert and allen hughes .
getting the hughes brothers to direct this seems almost as ludicrous as casting carrot top in , well , anything , but riddle me this : who better to direct a film that's set in the ghetto and features really violent street crime than the mad geniuses behind menace ii society ?
the ghetto in question is , of course , whitechapel in 1888 london's east end .
it's a filthy , sooty place where the whores ( called " unfortunates " ) are starting to get a little nervous about this mysterious psychopath who has been carving through their profession with surgical precision .
when the first stiff turns up , copper peter godley ( robbie coltrane , the world is not enough ) calls in inspector frederick abberline ( johnny depp , blow ) to crack the case .
abberline , a widower , has prophetic dreams he unsuccessfully tries to quell with copious amounts of absinthe and opium .
upon arriving in whitechapel , he befriends an unfortunate named mary kelly ( heather graham , say it isn't so ) and proceeds to investigate the horribly gruesome crimes that even the police surgeon can't stomach .
i don't think anyone needs to be briefed on jack the ripper , so i won't go into the particulars here , other than to say moore and campbell have a unique and interesting theory about both the identity of the killer and the reasons he chooses to slay .
in the comic , they don't bother cloaking the identity of the ripper , but screenwriters terry hayes ( vertical limit ) and rafael yglesias ( les mis ? rables ) do a good job of keeping him hidden from viewers until the very end .
it's funny to watch the locals blindly point the finger of blame at jews and indians because , after all , an englishman could never be capable of committing such ghastly acts .
and from hell's ending had me whistling the stonecutters song from the simpsons for days ( " who holds back the electric car/who made steve guttenberg a star ? " ) .
don't worry - it'll all make sense when you see it .
now onto from hell's appearance : it's certainly dark and bleak enough , and it's surprising to see how much more it looks like a tim burton film than planet of the apes did ( at times , it seems like sleepy hollow 2 ) .
the print i saw wasn't completely finished ( both color and music had not been finalized , so no comments about marilyn manson ) , but cinematographer peter deming ( don't say a word ) ably captures the dreariness of victorian-era london and helped make the flashy killing scenes remind me of the crazy flashbacks in twin peaks , even though the violence in the film pales in comparison to that in the black-and-white comic .
oscar winner martin childs' ( shakespeare in love ) production design turns the original prague surroundings into one creepy place .
even the acting in from hell is solid , with the dreamy depp turning in a typically strong performance and deftly handling a british accent .
ians holm ( joe gould's secret ) and richardson ( 102 dalmatians ) log in great supporting roles , but the big surprise here is graham .
i cringed the first time she opened her mouth , imagining her attempt at an irish accent , but it actually wasn't half bad .
the film , however , is all good .
2 : 00 - r for strong violence/gore , sexuality , language and drug content

In [16]:
# One negative review

In [17]:
print("\nNegative Review:\n")
print(data[data['target'] == 0]['review'].iloc[0])

Negative Review:

plot : two teen couples go to a church party , drink and then drive .
they get into an accident .
one of the guys dies , but his girlfriend continues to see him in her life , and has nightmares .
what's the deal ?
watch the movie and " sorta " find out . . .
critique : a mind-fuck movie for the teen generation that touches on a very cool idea , but presents it in a very bad package .
which is what makes this review an even harder one to write , since i generally applaud films which attempt to break the mold , mess with your head and such ( lost highway & memento ) , but there are good and bad ways of making all types of films , and these folks just didn't snag this one correctly .
they seem to have taken this pretty neat concept , but executed it terribly .
so what are the problems with the movie ?
well , its main problem is that it's simply too jumbled .
it starts off " normal " but then downshifts into this " fantasy " world in which you , as an audience member , have no idea what's going on .
there are dreams , there are characters coming back from the dead , there are others who look like the dead , there are strange apparitions , there are disappearances , there are a looooot of chase scenes , there are tons of weird things that happen , and most of it is simply not explained .
now i personally don't mind trying to unravel a film every now and then , but when all it does is give me the same clue over and over again , i get kind of fed up after a while , which is this film's biggest problem .
it's obviously got this big secret to hide , but it seems to want to hide it completely until its final five minutes .
and do they make things entertaining , thrilling or even engaging , in the meantime ?
not really .
the sad part is that the arrow and i both dig on flicks like this , so we actually figured most of it out by the half-way point , so all of the strangeness after that did start to make a little bit of sense , but it still didn't the make the film all that more entertaining .
i guess the bottom line with movies like this is that you should always make sure that the audience is " into it " even before they are given the secret password to enter your world of understanding .
i mean , showing melissa sagemiller running away from visions for about 20 minutes throughout the movie is just plain lazy ! !
okay , we get it . . . there
are people chasing her and we don't know who they are .
do we really need to see it over and over again ?
how about giving us different scenes offering further insight into all of the strangeness going down in the movie ?
apparently , the studio took this film away from its director and chopped it up themselves , and it shows .
there might've been a pretty decent teen mind-fuck movie in here somewhere , but i guess " the suits " decided that turning it into a music video with little edge , would make more sense .
the actors are pretty good for the most part , although wes bentley just seemed to be playing the exact same character that he did in american beauty , only in a new neighborhood .
but my biggest kudos go out to sagemiller , who holds her own throughout the entire film , and actually has you feeling her character's unraveling .
overall , the film doesn't stick because it doesn't entertain , it's confusing , it rarely excites and it feels pretty redundant for most of its runtime , despite a pretty cool ending and explanation to all of the craziness that came before it .
oh , and by the way , this is not a horror or teen slasher flick . . . it's
just packaged to look that way because someone is apparently assuming that the genre is still hot with the kids .
it also wrapped production two years ago and has been sitting on the shelves ever since .
whatever . . . skip
it !
where's joblo coming from ?
a nightmare of elm street 3 ( 7/10 ) - blair witch 2 ( 7/10 ) - the crow ( 9/10 ) - the crow : salvation ( 4/10 ) - lost highway ( 10/10 ) - memento ( 10/10 ) - the others ( 9/10 ) - stir of echoes ( 8/10 )

In [18]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
# Take one review

In [20]:
review = data['review'][0]

In [21]:
# Tokenization

In [22]:
tokens = word_tokenize(review)

In [23]:
# Remove Stopwords

In [24]:
stop_words = set(stopwords.words('english'))

filtered_words = [word for word in tokens if word.lower() not in stop_words]

print(filtered_words[:20])

['plot', ':', 'two', 'teen', 'couples', 'go', 'church', 'party', ',', 'drink', 'drive', '.', 'get', 'accident', '.', 'one', 'guys', 'dies', ',', 'girlfriend']

In [25]:
# Total rows
print("Total Reviews:", data.shape[0])

# Vocabulary size
cv = CountVectorizer()

X = cv.fit_transform(data['review'])

print("Total Vocabulary:", len(cv.vocabulary_))

Total Reviews: 2000
Total Vocabulary: 39659

In [29]:
 # Convert all review in small letters

In [26]:
data['review'] = data['review'].str.lower()

data.head()

   Unnamed: 0                                             review  target
0           0  plot : two teen couples go to a church party ,...       0
1           1  the happy bastard's quick movie review \ndamn ...       0
2           2  it is movies like these that make a jaded movi...       0
3           3   " quest for camelot " is warner bros . ' firs...       0
4           4  synopsis : a mentally unstable man undergoing ...       0

In [30]:
# Apply stemming technique on review data

In [27]:
ps = PorterStemmer()

data['review'] = data['review'].apply(
    lambda x: " ".join([ps.stem(word) for word in x.split()])
)

data.head()

   Unnamed: 0                                             review  target
0           0  plot : two teen coupl go to a church parti , d...       0
1           1  the happi bastard' quick movi review damn that...       0
2           2  it is movi like these that make a jade movi vi...       0
3           3  " quest for camelot " is warner bro . ' first ...       0
4           4  synopsi : a mental unstabl man undergo psychot...       0

In [31]:
# Apply Bag of Word technique and convert into dataframe

In [28]:
cv = CountVectorizer(max_features=20)

X = cv.fit_transform(data['review'])

bow_df = pd.DataFrame(X.toarray(), columns=cv.get_feature_names_out())

bow_df.head()

,and,are,as,be,but,film,for,he,hi,in,is,it,movi,of,on,that,the,thi,to,with
0,20,13,1,1,10,8,4,1,1,8,12,29,7,16,4,13,38,10,16,5
1,8,1,0,0,0,0,2,1,0,4,3,4,5,8,3,4,13,2,2,1
2,12,3,6,3,1,9,2,1,0,2,17,10,3,13,8,13,42,3,6,3
3,11,4,6,6,4,1,6,0,0,4,6,9,0,11,3,6,21,5,14,6
4,17,4,8,8,2,3,6,8,3,14,18,13,3,15,5,8,48,6,26,1

In [32]:
# Difference between stemming and lemmatization ?

In [35]:
# | Stemming                                   | Lemmatization                              |
# | Removes suffix from words to get root form | Converts word to its dictionary base form  |
# | Uses simple rules                          | Uses vocabulary and morphological analysis |
# | Faster but less accurate                   | Slower but more accurate                   |

# Example:

# Stemming:
# playing → play
# studies → studi

# Lemmatization:
# playing → play
# studies → study

In [36]:
# Describe corpus and how you can create it

In [37]:
# Corpus is a collection of text documents used for Natural Language Processing tasks.

# Examples of corpus:

# movie reviews

# news articles

# tweets

# We can create a corpus by collecting multiple text documents in a list.

# Example in Python:

# corpus = [
# "This movie is amazing",
# "I love learning NLP",
# "Python makes text analysis easy"
# ]

# Corpus can be obtained from:

# NLTK datasets

# Kaggle datasets

# Web scraping

# Text files

In [39]:
# Explain Bag of word technique.

In [38]:
# Bag of Words (BoW) is a technique used to convert text data into numerical features by counting the frequency of words in a document.

# Example:

# Sentence 1:
# "I love NLP"

# Sentence 2:
# "I love Python"

# Vocabulary:

# I, love, NLP, Python

# Vector representation:

# Sentence	I	love	NLP	Python
# S1	1	1	1	0
# S2	1	1	0	1

# Python Example:

# from sklearn.feature_extraction.text import CountVectorizer

# corpus = ["I love NLP", "I love Python"]

# cv = CountVectorizer()
# X = cv.fit_transform(corpus)

# print(X.toarray())

In [40]:
# Describe pipeline of nlp.

In [41]:
# The NLP pipeline is a sequence of steps used to process and analyze text data.

# Steps in NLP pipeline:

# Text Collection – gather text data

# Text Cleaning – remove punctuation and special characters

# Tokenization – split text into words

# Stopword Removal – remove common words like is, the

# Stemming/Lemmatization – convert words to root form

# Feature Extraction – Bag of Words / TF-IDF

# Model Building – classification or prediction

In [42]:
# Write syntax for removing special characters from text.

In [44]:
import re

text = "Hello!!! NLP SESSIONAL @2026"

clean_text = re.sub(r'[^a-zA-Z0-9 ]', '', text)

print(clean_text)

Hello NLP SESSIONAL 2026